server:
    port: 8081

spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080/auth/realms/DFA
                    jwk-set-uri: http://localhost:8080/auth/realms/DFA/protocol/openid-connect/certs

springdoc:
    swagger-ui:
        path: /swagger-ui.html
