server:
    port: 8081


springdoc:
    swagger-ui:
        path: /swagger-ui.html

spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080/auth/realms/DFA
                    jwk-set-uri: http://localhost:8080/auth/realms/DFA/protocol/openid-connect/certs
    datasource:
        url: jdbc:postgresql://localhost:5433/dfa
        username: postgres
        password: postgres
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db-changelog.xml

app:
    config:
        async:
            max-thread-pool-size: 10
        cache:
            ttl: 1000000 # ms
    integration:
        providers:
            klever:
                assets-url: https://api.mainnet.klever.finance/v1.0/assets/list